// src/components/Card/Paging.jsx
import React, { useContext } from "react";
import ButtonGroup from "reactstrap/lib/ButtonGroup";
import ButtonToolbar from "reactstrap/lib/ButtonToolbar";

const Paging = (props) => {
	let info = props.pageInfo.pageInfos;
	info.nowPage = info.nowPage === 0 ? 1 : info.nowPage;
	info.totalPage = Math.ceil(info.totalCount / info.pageSize);
	let myRound = Math.floor(info.nowPage / info.pageSize);
	info.startPage = myRound * info.pageSize;
	info.endPage = info.startPage + info.pageListSize - 1;

	let domList = [];
	if (info.startPage > 1) {
		domList.push(
			<button
				type="button"
				className="btn btn-primary btn-sm"
				key="start"
				onClick={() => {
					info.endPage = info.startPage - 1;
					info.startPage = info.endPage - (info.pageListSize - 1);
					info.nowPage = info.endPage;
					fnSearch();
				}}
			>
				←
			</button>
		);
	}
	let end = info.endPage <= info.totalPage ? info.endPage : info.totalPage;
	for (let i = info.startPage; i <= end; i++) {
		if (i > 0) {
			if (i === info.nowPage) {
				domList.push(
					<button type="button" className="btn btn-primary btn-sm active" key={i}>
						{i}
					</button>
				);
			} else {
				domList.push(
					<button
						type="button"
						className="btn btn-primary btn-sm"
						onClick={() => {
							info.nowPage = i;
							fnSearch();
						}}
						key={i}
					>
						{i}
					</button>
				);
			}
		}
	}
	if (info.endPage < info.totalPage) {
		domList.push(
			<button
				type="button"
				className="btn btn-primary btn-sm"
				key="end"
				onClick={() => {
					info.startPage = info.endPage + 1;
					info.nowPage = info.startPage;
					fnSearch();
				}}
			>
				→
			</button>
		);
	}

	function fnSearch(e) {
		if (e) e.preventDefault();
		props.search();
	}

	return (
		<ButtonToolbar>
			<ButtonGroup className="mr-2" size="sm">
				{domList.map((item) => item)}
			</ButtonGroup>
		</ButtonToolbar>
	);
};

export default Paging;

// src/components/Paging.svelte
<script>
	import { paging } from "../stores";
	export let fnSearch;
	export let pageSize;
	export let totalCount;
	export let fnDelete;
	export let registUrl;
	let nowPage = 0;
	let totalPage = 0;
	let myRound = 0;
	let startPage = 0;
	let endPage = 0;
	let end = 0;
	let pages = [];
	$: {
		if (totalCount > 0) {
			pages = [];
			nowPage = $paging.nowPage === 0 ? 1 : $paging.nowPage;
			totalPage = Math.ceil(totalCount / pageSize);
			myRound = Math.floor(nowPage / pageSize);
			startPage = myRound * pageSize;
			endPage = startPage + $paging.pageListSize - 1;
			end = endPage <= totalPage ? endPage : totalPage;
			let o = $paging;
			o.nowPage = nowPage;
			o.totalCount = totalCount;
			o.totalPage = totalPage;
			o.pageSize = pageSize;
			o.startPage = startPage;
			o.endPage = endPage;
			paging.update((paging) => o);
			for (let i = startPage; i <= end; i++) {
				pages = [...pages, i];
			}
		}
	}
</script>

<table class="table">
	<tr>
		<td width="100">
			<div class="demo-inline-spacing">
				<button type="button" class="btn btn-danger" on:click={fnDelete}>삭제</button>
			</div>
		</td>
		<td width="*">
			<nav aria-label="Page navigation">
				<ul class="pagination justify-content-center">
					{#if startPage > 1}
						<li class="page-item prev">
							<span
								class="page-link"
								on:click={() => {
									$paging.endPage = $paging.startPage - 1;
									$paging.startPage = $paging.endPage - ($paging.pageListSize - 1);
									$paging.nowPage = $paging.endPage;
									fnSearch();
								}}
							>
								<i class="tf-icon bx bx-chevrons-left" />
							</span>
						</li>
					{/if}

					{#each pages as page}
						{#if page > 0}
							{#if nowPage === page}
								<li class="page-item active">
									<span class="page-link">{page}</span>
								</li>
							{:else}
								<li class="page-item">
									<span
										class="page-link"
										on:click={() => {
											let o = $paging;
											o.nowPage = page;
											paging.update((paging) => o);
											fnSearch();
										}}
										style="cursor:pointer"
									>
										{page}
									</span>
								</li>
							{/if}
						{/if}
					{/each}

					{#if endPage < totalPage}
						<li class="page-item next">
							<span
								class="page-link"
								on:click={() => {
									$paging.startPage = $paging.endPage + 1;
									$paging.nowPage = $paging.startPage;
									fnSearch();
								}}
							>
								<i class="tf-icon bx bx-chevrons-right" />
							</span>
						</li>
					{/if}
				</ul>
			</nav>
		</td>
		<td width="100">
			{#if registUrl}
				<div class="demo-inline-spacing">
					<a href={registUrl}>
						<button type="button" class="btn btn-primary">등록</button>
					</a>
				</div>
			{/if}
		</td>
	</tr>
</table>
